stages:
  - build
  - deploy

build:
  stage: build
  image: docker:24

  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""

  services:
    - name: docker:24-dind
      command: ["--tls=false"]

  script:
    - docker info
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

    - docker build -f docker/frontend.Dockerfile -t $CI_REGISTRY_IMAGE/cardimedfrontend:$CI_COMMIT_SHA ./frontend
    - docker push $CI_REGISTRY_IMAGE/cardimedfrontend:$CI_COMMIT_SHA

    - docker build -f docker/api.Dockerfile -t $CI_REGISTRY_IMAGE/cardimedbackend:$CI_COMMIT_SHA ./backend
    - docker push $CI_REGISTRY_IMAGE/cardimedbackend:$CI_COMMIT_SHA


deploy:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""]

  variables:
    IMAGE_TAG: $CI_COMMIT_SHA
    K8S_NAMESPACE: cardimed

  script:
    - kubectl config use-context rd-devs/k8s-connecttion:rnddevs-k8s-connection

    # namespace first
    - kubectl apply -f k8s-files/00-namespace.yaml

    # registry secret (idempotent)
    - kubectl delete secret gitlab-registry -n $K8S_NAMESPACE --ignore-not-found
    - kubectl create secret docker-registry gitlab-registry
        --docker-server="$CI_REGISTRY"
        --docker-username="$CI_REGISTRY_USER"
        --docker-password="$CI_REGISTRY_PASSWORD"
        --docker-email="${GITLAB_USER_EMAIL:-$CI_COMMIT_AUTHOR_EMAIL}"
        -n $K8S_NAMESPACE

    # # static resources
    # - kubectl apply -f k8s-files/01-secrets.yaml
    # - kubectl apply -f k8s-files/02-postgres.yaml
    # - kubectl apply -f k8s-files/03-mosquitto.yaml

    # # templated deployments
    # - export IMAGE_TAG=$CI_COMMIT_SHA
    # - envsubst < k8s-files/04-api.yaml > /tmp/api.yaml
    # - envsubst < k8s-files/05-frontend.yaml > /tmp/frontend.yaml

    # - kubectl apply -f /tmp/api.yaml
    # - kubectl apply -f /tmp/frontend.yaml
    # - kubectl apply -f k8s-files/06-ingress.yaml

    # # rollout safety
    # - kubectl rollout status deployment/api-server -n $K8S_NAMESPACE --timeout=300s
    # - kubectl rollout status deployment/frontend -n $K8S_NAMESPACE --timeout=300s