stages:
  - build
  - deploy

build:
  stage: build
  image: docker:24
  services:
    - name: docker:24-dind
      command: ["--tls=false"]
  script:

    - docker info
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build -f docker/frontend.Dockerfile -t $CI_REGISTRY_IMAGE/cardimedfrontend:$CI_COMMIT_SHA ./frontend
    - docker push $CI_REGISTRY_IMAGE/cardimedfrontend:$CI_COMMIT_SHA
    - docker build -f docker/api.Dockerfile -t $CI_REGISTRY_IMAGE/cardimedbackend:$CI_COMMIT_SHA ./backend
    - docker push $CI_REGISTRY_IMAGE/cardimedbackend:$CI_COMMIT_SHA

  # rules:
  #   - if: '$CI_COMMIT_BRANCH == "main"'

deploy:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""]

  variables:
    IMAGE_TAG: $CI_COMMIT_SHA
    K8S_NAMESPACE: cardimed

  script:
    - kubectl config use-context rd-devs/k8s-connecttion:rnddevs-k8s-connection
    - kubectl apply --validate=false --insecure-skip-tls-verify -f k8s/namespace.yaml
    - kubectl delete secret gitlab-registry -n $K8S_NAMESPACE --ignore-not-found --insecure-skip-tls-verify
    - |
      kubectl create secret docker-registry gitlab-registry \
        --docker-server="$CI_REGISTRY" \
        --docker-username="$CI_REGISTRY_USER" \
        --docker-password="$CI_REGISTRY_PASSWORD" \
        --docker-email="${GITLAB_USER_EMAIL:-$CI_COMMIT_AUTHOR_EMAIL}" \
        -n $K8S_NAMESPACE --insecure-skip-tls-verify
    - kubectl apply --validate=false --insecure-skip-tls-verify -f k8s/secrets.yaml
    - kubectl apply --validate=false --insecure-skip-tls-verify -f k8s/postgres.yaml

    - export IMAGE_TAG=$CI_COMMIT_SHA
    - envsubst < k8s/api.yaml      > /tmp/api.yaml
    - envsubst < k8s/frontend.yaml > /tmp/frontend.yaml

    - kubectl apply --validate=false --insecure-skip-tls-verify -f /tmp/api.yaml
    - kubectl apply --validate=false --insecure-skip-tls-verify -f /tmp/frontend.yaml
    - kubectl apply --validate=false --insecure-skip-tls-verify -f k8s/ingress.yaml

    - kubectl rollout restart deployment/api-server --insecure-skip-tls-verify -n $K8S_NAMESPACE
    - kubectl rollout restart deployment/frontend --insecure-skip-tls-verify -n $K8S_NAMESPACE
    - kubectl rollout status deployment/api-server --insecure-skip-tls-verify -n $K8S_NAMESPACE --timeout=300s
    - kubectl rollout status deployment/frontend   --insecure-skip-tls-verify -n $K8S_NAMESPACE --timeout=300s
  # rules:
  #   - if: '$CI_COMMIT_BRANCH == "main"'