version: "2"
linters:
  enable:
    - durationcheck
    - errname
    - gocritic
    - gosec
    - misspell
    - revive
    - thelper
    - unconvert
  settings:
    errcheck:
      check-blank: true
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
    revive:
      rules:
        - name: exported
          disabled: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gocritic
        path: _test.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
