apiVersion: v1
kind: Secret
metadata:
  name: cardimed-secrets
  namespace: cardimed
type: Opaque
stringData:
  POSTGRES_PASSWORD: pkGVFXiT6NePhBPiBYG+nNYezbGBRcPLFuaDb7Qy1eg=
  JWT_SECRET: QYV388/oT7+X8W6k9aqptQX0cBkicgmuiCCS6rjrr4JEorx6ESfE7GAImxIus2j/
  ADMIN_PASSWORD: yv2C1rjdn1AcQpesa9dgldWKNYtIEnvhvW6XWXA3EmY=
  MQTT_BROKERS: '[{"name":"coreic","broker":"mqtt.coreic.eu","port":8883,"topic":"CARDIMED/EBOS/DEMO_9/#","qos":1,"tls":true,"username":"ebos","password":"vgbwEkGUfD3QXsh9ZAxYuW"}]'